### ISSUE TITLE
Xenokit doesn't equip the partset I want

### ISSUE THREAD

**Issue by Viniciaao** [LazyBone152/XenoKit#15]
this problem only started to happen only in version 0.1.3, I can't apply a partset for me to see

edit:
it seems that, it only applies if I leave the program in the background, I come back, I leave it in the background again, it will only now appear

**Comment by LazyBone152** [comment]
Is there a particular character and partset that this happens with? I'm unable to reproduce the issue with any of Goku's partsets.
