### ISSUE TITLE
Skill Vox does not load

### ISSUE THREAD

**Issue by Viniciaao** [LazyBone152/XenoKit#19]
if the skill vox is in a different folder like this
"VOX/Battle/skill/example/CAR_BTL_example_ABC_VOX.acb"
in English:"VOX/Battle/skill/example/en/CAR_BTL_example_ABC_VOX.acb".

The game loads the vox normally, but Xenokit can't load it, so it would be good if Xenokit behaved like the game and could read it.

**Comment by LazyBone152** [comment]
I've added support for this in v0.3, but i wasn't able to test it. Can you verify if it works as expected?

**Comment by Viniciaao** [comment]
It still didn't work

**Comment by LazyBone152** [comment]
Should now be fixed in 0.3.2.
