### ISSUE TITLE
EyeMovement not working properly

### ISSUE THREAD

**Issue by Viniciaao** [LazyBone152/XenoKit#23]
EyeMovement is not showing correctly in the xenokit, but in-game it shows
![Capturar](https://github.com/LazyBone152/XenoKit/assets/70339220/1205b32d-0c91-49a0-9da5-4b76437cc1fd)

**Comment by LazyBone152** [comment]
Somehow I missed this... 

Anyway, this has just been fixed in commit [9c31a4a](https://github.com/LazyBone152/XenoKit/commit/9c31a4a23c37af1a2d7c2c74b3464aa4ab4e9097)

**Comment by Viniciaao** [comment]
Thanks bro, I'll test this later to see if it's actually working.

Em qui., 22 de ago. de 2024 22:32, LazyBone152 ***@***.***>
escreveu:
