### ISSUE TITLE
EyeMovement no longer displays

### ISSUE THREAD

**Issue by halloweenpandas** [LazyBone152/XenoKit#33]
Since a few updates ago both BAC eye movement and "baked" eye movement (primary face animation) stopped working
![image](https://github.com/LazyBone152/XenoKit/assets/51948142/f0946f0b-b66c-4a46-8af3-268289845eba)
^ As you can see in this image there should be eye movement played through the BAC but it's not showing up in the preview.

![image](https://github.com/LazyBone152/XenoKit/assets/51948142/2701f227-7505-4998-9755-dd00c5f23f6c)
^ It also doesn't work in the animation viewer, where at this point he should have eye movement in his stance

I've debugged it a little myself and it might be shader related(?) but I'm not too sure

**Comment by LazyBone152** [comment]
Fixed in [9c31a4a](https://github.com/LazyBone152/XenoKit/commit/9c31a4a23c37af1a2d7c2c74b3464aa4ab4e9097)

Yeah it was shader related, and seems to have been broken since 0.2 when I reworked shaders and added particles. I'm surprised it wasn't reported back then
