### ISSUE TITLE
Unhandled Exception while trying to load Blast Skill 21091 (MGA)

### ISSUE THREAD

**Issue by HirumaBSK** [LazyBone152/XenoKit#38]
This error happens regardless of whether _Only Load from CPK_ is checked or not

System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Xv2CoreLib.Xenoverse2.GetSkillFolderName(Skill cusEntry) en C:\source\XenoverseTools\XV2 Tools\Xv2CoreLib\Xenoverse2\Xenoverse2.cs:línea 709
   en Xv2CoreLib.Xenoverse2.GetSkillFiles(Skill cusEntry, SkillType skillType, Boolean loadSkillFiles, Boolean loadFromCpk) en C:\source\XenoverseTools\XV2 Tools\Xv2CoreLib\Xenoverse2\Xenoverse2.cs:línea 430
   en Xv2CoreLib.Xenoverse2.GetSkill(SkillType skillType, Int32 id1, Boolean loadFiles, Boolean onlyLoadFromCPK) en C:\source\XenoverseTools\XV2 Tools\Xv2CoreLib\Xenoverse2\Xenoverse2.cs:línea 411
   en XenoKit.Editor.Files.<>c__DisplayClass46_0.<<AsyncLoadSkill>b__0>d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en XenoKit.Editor.Files.<AsyncLoadSkill>d__46.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en XenoKit.Editor.Files.<AsyncLoadSkill>d__46.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en XenoKit.Editor.Files.<AsyncLoadSkill>d__46.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en XenoKit.Editor.Files.<AsyncLoadSkill>d__45.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by LazyBone152** [comment]
Fixed in [93a5b97](https://github.com/LazyBone152/XV2-Tools/commit/93a5b97df85fbaa417f388da6aa650f3408c029b)
