### ISSUE TITLE
Roll is mirrored in the viewport (CamEAN)

### ISSUE THREAD

**Issue by UnleashedGH** [LazyBone152/XenoKit#4]
when playing animations from CamEAN, Roll plays mirrored in the viewport

Ex: Godly Display Action Entry #22 (Incorrect Roll)
![image](https://github.com/LazyBone152/XenoKit/assets/47185022/5c79fef4-2ebb-46c4-b105-454ced66a906)

Flipping the Roll value fixes it

![image](https://github.com/LazyBone152/XenoKit/assets/47185022/e71b1fe8-3ed4-4811-8f1e-410a7d947471)

seems that multiplying the result for GetCurrentRoll in Camera  by -1 should fix the issue
also doing the same when setting the Roll value in CameraTabView to save correctly

This does not apply to RotationZ in BACType10 offsets, it both plays and saves properly

**Comment by LazyBone152** [comment]
Fixed with 0.1.1
